apiVersion: apps/v1
kind: Deployment
metadata:
  name: chippie-deployment
  labels:
    app: chippie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chippie
  template:
    metadata:
      labels:
        app: chippie
    spec:
      containers:
      - name: chippie
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: ENVIRONMENT
            value: {{ .Values.environment }}
          - name: PR_NUMBER
            value: {{ .Values.pr | quote }}
          - name: JWT_AUTH_SECRET
            valueFrom:
              secretKeyRef:
                name: jwt-auth-secret
                key: JWT_AUTH_SECRET
          - name: JWT_REFRESH_SECRET
            valueFrom:
              secretKeyRef:
                name: jwt-refresh-secret
                key: JWT_REFRESH_SECRET
          - name: DB_PASSWORD
            value: {{ .Values.secrets.db_password | quote }}
        ports:
          - containerPort: {{ .Values.service.port }}